version: "3.6"
services:
  db:
    build:
      context: ../db
    restart: always
    networks:
      registrator-network:
        ipv4_address: 10.5.0.2

  backend:
    image: registrator/backend
    ports:
      - "8080"
    networks:
      registrator-network:
        ipv4_address: 10.5.0.3

networks:
  registrator-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

volumes:
  db-data: